# Generated by Django 4.2 on 2023-04-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0004_linkup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkup',
            name='location',
        ),
    ]
