# Generated by Django 4.2 on 2023-04-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0006_linkup_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
