# Generated by Django 4.2 on 2023-04-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0008_attendees_linkup_attendees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendees',
            new_name='Attendee',
        ),
        migrations.AddField(
            model_name='linkup',
            name='date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkup',
            name='organizer_email',
            field=models.EmailField(default='max@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
